import React from 'react';
import ReactDOM from 'react-dom';
import Header from './Header';
import Footer from './Footer';
import ModalWindow from './ModalWindow';


class FullSite extends React.Component {
    render() {       
        return (
            <div>
                <Header/>            
                <main className="b-main">
                    <div className="container">
                    <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet velit sagittis mauris egestas cursus. Nullam vitae nibh nisi. Suspendisse convallis eros sapien, nec tempor lorem lobortis nec. Cras a faucibus dui. Curabitur ac laoreet turpis, a maximus ligula. Praesent ut lectus ac augue fringilla vehicula sed sit amet dui. Cras nulla mauris, maximus vitae nulla ac, elementum maximus enim. Curabitur fermentum et metus accumsan elementum. In tempus nulla felis, vel porttitor neque semper nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus erat, euismod sed erat vel, condimentum mollis nisl.
                        </p>
                        <p>
                            Sed at augue in felis euismod tincidunt. Mauris vel massa nisl. Quisque iaculis sollicitudin tempor. Suspendisse nec augue ut urna viverra varius sed consectetur nulla. Nunc fringilla ligula nec pulvinar facilisis. Curabitur felis tortor, tempus eget tempor eu, viverra a libero. Sed nisl tellus, mollis quis malesuada nec, mollis quis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae tellus vitae nisi interdum molestie. Proin rutrum rhoncus porttitor. Integer sit amet molestie tortor. Nam vel urna eu nisl lobortis ultrices ut a ligula. Aliquam nec facilisis felis, ut porta tellus. Etiam fermentum egestas nisi, eget vestibulum ligula eleifend vitae. Integer pulvinar lectus eget erat porttitor maximus.
                        </p>
                        <p>
                            Integer elit magna, aliquam a auctor eu, commodo sed risus. Maecenas malesuada aliquet urna, convallis feugiat tellus dictum ut. Phasellus eget diam suscipit, scelerisque justo id, faucibus ex. In venenatis sapien ipsum. Morbi semper interdum magna, quis mollis lorem viverra nec. Aliquam erat volutpat. Morbi consequat purus quis nisi laoreet, sed facilisis eros accumsan. Donec suscipit mauris a molestie varius. Aenean sem purus, sollicitudin id lectus quis, egestas dignissim ante. Aenean nibh ex, sollicitudin ac lectus id, condimentum euismod velit. Nulla aliquam, eros vel maximus suscipit, libero nisl suscipit est, quis condimentum justo tortor a urna. Aliquam sollicitudin enim non tempor efficitur.
                        </p>
                        <p>
                            Nam fermentum quam ac faucibus mattis. Fusce mi magna, convallis varius sagittis non, euismod quis sem. Suspendisse ultricies, ante elementum vehicula euismod, arcu quam volutpat diam, eu iaculis lacus tellus eu elit. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nisl accumsan, hendrerit ex quis, luctus nulla. Donec tincidunt lacus quis ex vehicula porta. Praesent sit amet ex non eros accumsan consectetur sit amet et odio. Donec sed dolor a lorem viverra viverra. Nam sollicitudin leo eu pharetra mattis. Nullam magna orci, imperdiet eget nulla tempor, pretium aliquet leo. Curabitur faucibus, tortor commodo maximus porta, justo ex pretium turpis, eget iaculis mi magna ac augue. Aliquam sem sem, consequat at urna eu, vulputate posuere tortor. Morbi in orci aliquam lectus fringilla aliquet vel eget turpis. Integer iaculis tortor vitae mollis luctus.
                        </p>
                        <p>
                            Mauris vel ipsum convallis, lacinia diam et, iaculis ligula. Maecenas ac vehicula metus. Suspendisse a augue in enim iaculis blandit. Donec a erat odio. Nullam mollis magna quis pellentesque pharetra. Vestibulum luctus sodales leo sagittis mollis. Mauris blandit, tellus volutpat ultricies ullamcorper, sapien quam condimentum turpis, et bibendum nulla quam ut diam. Nullam lectus quam, elementum ut orci quis, euismod vulputate ante. Nunc ligula arcu, tristique a tincidunt quis, scelerisque eget ex. Nam semper, nunc ut gravida rhoncus, sem nisi malesuada elit, a facilisis tortor velit id magna. Nam dui ex, faucibus nec vestibulum non, lobortis quis sem. Phasellus pretium arcu odio, consectetur vulputate justo auctor sed. Integer sodales ipsum risus, sed mattis lectus commodo ut.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet velit sagittis mauris egestas cursus. Nullam vitae nibh nisi. Suspendisse convallis eros sapien, nec tempor lorem lobortis nec. Cras a faucibus dui. Curabitur ac laoreet turpis, a maximus ligula. Praesent ut lectus ac augue fringilla vehicula sed sit amet dui. Cras nulla mauris, maximus vitae nulla ac, elementum maximus enim. Curabitur fermentum et metus accumsan elementum. In tempus nulla felis, vel porttitor neque semper nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus erat, euismod sed erat vel, condimentum mollis nisl.
                        </p>
                        <p>
                            Sed at augue in felis euismod tincidunt. Mauris vel massa nisl. Quisque iaculis sollicitudin tempor. Suspendisse nec augue ut urna viverra varius sed consectetur nulla. Nunc fringilla ligula nec pulvinar facilisis. Curabitur felis tortor, tempus eget tempor eu, viverra a libero. Sed nisl tellus, mollis quis malesuada nec, mollis quis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae tellus vitae nisi interdum molestie. Proin rutrum rhoncus porttitor. Integer sit amet molestie tortor. Nam vel urna eu nisl lobortis ultrices ut a ligula. Aliquam nec facilisis felis, ut porta tellus. Etiam fermentum egestas nisi, eget vestibulum ligula eleifend vitae. Integer pulvinar lectus eget erat porttitor maximus.
                        </p>
                        <p>
                            Integer elit magna, aliquam a auctor eu, commodo sed risus. Maecenas malesuada aliquet urna, convallis feugiat tellus dictum ut. Phasellus eget diam suscipit, scelerisque justo id, faucibus ex. In venenatis sapien ipsum. Morbi semper interdum magna, quis mollis lorem viverra nec. Aliquam erat volutpat. Morbi consequat purus quis nisi laoreet, sed facilisis eros accumsan. Donec suscipit mauris a molestie varius. Aenean sem purus, sollicitudin id lectus quis, egestas dignissim ante. Aenean nibh ex, sollicitudin ac lectus id, condimentum euismod velit. Nulla aliquam, eros vel maximus suscipit, libero nisl suscipit est, quis condimentum justo tortor a urna. Aliquam sollicitudin enim non tempor efficitur.
                        </p>
                        <p>
                            Nam fermentum quam ac faucibus mattis. Fusce mi magna, convallis varius sagittis non, euismod quis sem. Suspendisse ultricies, ante elementum vehicula euismod, arcu quam volutpat diam, eu iaculis lacus tellus eu elit. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nisl accumsan, hendrerit ex quis, luctus nulla. Donec tincidunt lacus quis ex vehicula porta. Praesent sit amet ex non eros accumsan consectetur sit amet et odio. Donec sed dolor a lorem viverra viverra. Nam sollicitudin leo eu pharetra mattis. Nullam magna orci, imperdiet eget nulla tempor, pretium aliquet leo. Curabitur faucibus, tortor commodo maximus porta, justo ex pretium turpis, eget iaculis mi magna ac augue. Aliquam sem sem, consequat at urna eu, vulputate posuere tortor. Morbi in orci aliquam lectus fringilla aliquet vel eget turpis. Integer iaculis tortor vitae mollis luctus.
                        </p>
                        <p>
                            Mauris vel ipsum convallis, lacinia diam et, iaculis ligula. Maecenas ac vehicula metus. Suspendisse a augue in enim iaculis blandit. Donec a erat odio. Nullam mollis magna quis pellentesque pharetra. Vestibulum luctus sodales leo sagittis mollis. Mauris blandit, tellus volutpat ultricies ullamcorper, sapien quam condimentum turpis, et bibendum nulla quam ut diam. Nullam lectus quam, elementum ut orci quis, euismod vulputate ante. Nunc ligula arcu, tristique a tincidunt quis, scelerisque eget ex. Nam semper, nunc ut gravida rhoncus, sem nisi malesuada elit, a facilisis tortor velit id magna. Nam dui ex, faucibus nec vestibulum non, lobortis quis sem. Phasellus pretium arcu odio, consectetur vulputate justo auctor sed. Integer sodales ipsum risus, sed mattis lectus commodo ut.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet velit sagittis mauris egestas cursus. Nullam vitae nibh nisi. Suspendisse convallis eros sapien, nec tempor lorem lobortis nec. Cras a faucibus dui. Curabitur ac laoreet turpis, a maximus ligula. Praesent ut lectus ac augue fringilla vehicula sed sit amet dui. Cras nulla mauris, maximus vitae nulla ac, elementum maximus enim. Curabitur fermentum et metus accumsan elementum. In tempus nulla felis, vel porttitor neque semper nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus erat, euismod sed erat vel, condimentum mollis nisl.
                        </p>
                        <p>
                            Sed at augue in felis euismod tincidunt. Mauris vel massa nisl. Quisque iaculis sollicitudin tempor. Suspendisse nec augue ut urna viverra varius sed consectetur nulla. Nunc fringilla ligula nec pulvinar facilisis. Curabitur felis tortor, tempus eget tempor eu, viverra a libero. Sed nisl tellus, mollis quis malesuada nec, mollis quis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae tellus vitae nisi interdum molestie. Proin rutrum rhoncus porttitor. Integer sit amet molestie tortor. Nam vel urna eu nisl lobortis ultrices ut a ligula. Aliquam nec facilisis felis, ut porta tellus. Etiam fermentum egestas nisi, eget vestibulum ligula eleifend vitae. Integer pulvinar lectus eget erat porttitor maximus.
                        </p>
                        <p>
                            Integer elit magna, aliquam a auctor eu, commodo sed risus. Maecenas malesuada aliquet urna, convallis feugiat tellus dictum ut. Phasellus eget diam suscipit, scelerisque justo id, faucibus ex. In venenatis sapien ipsum. Morbi semper interdum magna, quis mollis lorem viverra nec. Aliquam erat volutpat. Morbi consequat purus quis nisi laoreet, sed facilisis eros accumsan. Donec suscipit mauris a molestie varius. Aenean sem purus, sollicitudin id lectus quis, egestas dignissim ante. Aenean nibh ex, sollicitudin ac lectus id, condimentum euismod velit. Nulla aliquam, eros vel maximus suscipit, libero nisl suscipit est, quis condimentum justo tortor a urna. Aliquam sollicitudin enim non tempor efficitur.
                        </p>
                        <p>
                            Nam fermentum quam ac faucibus mattis. Fusce mi magna, convallis varius sagittis non, euismod quis sem. Suspendisse ultricies, ante elementum vehicula euismod, arcu quam volutpat diam, eu iaculis lacus tellus eu elit. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nisl accumsan, hendrerit ex quis, luctus nulla. Donec tincidunt lacus quis ex vehicula porta. Praesent sit amet ex non eros accumsan consectetur sit amet et odio. Donec sed dolor a lorem viverra viverra. Nam sollicitudin leo eu pharetra mattis. Nullam magna orci, imperdiet eget nulla tempor, pretium aliquet leo. Curabitur faucibus, tortor commodo maximus porta, justo ex pretium turpis, eget iaculis mi magna ac augue. Aliquam sem sem, consequat at urna eu, vulputate posuere tortor. Morbi in orci aliquam lectus fringilla aliquet vel eget turpis. Integer iaculis tortor vitae mollis luctus.
                        </p>
                        <p>
                            Mauris vel ipsum convallis, lacinia diam et, iaculis ligula. Maecenas ac vehicula metus. Suspendisse a augue in enim iaculis blandit. Donec a erat odio. Nullam mollis magna quis pellentesque pharetra. Vestibulum luctus sodales leo sagittis mollis. Mauris blandit, tellus volutpat ultricies ullamcorper, sapien quam condimentum turpis, et bibendum nulla quam ut diam. Nullam lectus quam, elementum ut orci quis, euismod vulputate ante. Nunc ligula arcu, tristique a tincidunt quis, scelerisque eget ex. Nam semper, nunc ut gravida rhoncus, sem nisi malesuada elit, a facilisis tortor velit id magna. Nam dui ex, faucibus nec vestibulum non, lobortis quis sem. Phasellus pretium arcu odio, consectetur vulputate justo auctor sed. Integer sodales ipsum risus, sed mattis lectus commodo ut.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet velit sagittis mauris egestas cursus. Nullam vitae nibh nisi. Suspendisse convallis eros sapien, nec tempor lorem lobortis nec. Cras a faucibus dui. Curabitur ac laoreet turpis, a maximus ligula. Praesent ut lectus ac augue fringilla vehicula sed sit amet dui. Cras nulla mauris, maximus vitae nulla ac, elementum maximus enim. Curabitur fermentum et metus accumsan elementum. In tempus nulla felis, vel porttitor neque semper nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus erat, euismod sed erat vel, condimentum mollis nisl.
                        </p>
                        <p>
                            Sed at augue in felis euismod tincidunt. Mauris vel massa nisl. Quisque iaculis sollicitudin tempor. Suspendisse nec augue ut urna viverra varius sed consectetur nulla. Nunc fringilla ligula nec pulvinar facilisis. Curabitur felis tortor, tempus eget tempor eu, viverra a libero. Sed nisl tellus, mollis quis malesuada nec, mollis quis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae tellus vitae nisi interdum molestie. Proin rutrum rhoncus porttitor. Integer sit amet molestie tortor. Nam vel urna eu nisl lobortis ultrices ut a ligula. Aliquam nec facilisis felis, ut porta tellus. Etiam fermentum egestas nisi, eget vestibulum ligula eleifend vitae. Integer pulvinar lectus eget erat porttitor maximus.
                        </p>
                        <p>
                            Integer elit magna, aliquam a auctor eu, commodo sed risus. Maecenas malesuada aliquet urna, convallis feugiat tellus dictum ut. Phasellus eget diam suscipit, scelerisque justo id, faucibus ex. In venenatis sapien ipsum. Morbi semper interdum magna, quis mollis lorem viverra nec. Aliquam erat volutpat. Morbi consequat purus quis nisi laoreet, sed facilisis eros accumsan. Donec suscipit mauris a molestie varius. Aenean sem purus, sollicitudin id lectus quis, egestas dignissim ante. Aenean nibh ex, sollicitudin ac lectus id, condimentum euismod velit. Nulla aliquam, eros vel maximus suscipit, libero nisl suscipit est, quis condimentum justo tortor a urna. Aliquam sollicitudin enim non tempor efficitur.
                        </p>
                        <p>
                            Nam fermentum quam ac faucibus mattis. Fusce mi magna, convallis varius sagittis non, euismod quis sem. Suspendisse ultricies, ante elementum vehicula euismod, arcu quam volutpat diam, eu iaculis lacus tellus eu elit. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nisl accumsan, hendrerit ex quis, luctus nulla. Donec tincidunt lacus quis ex vehicula porta. Praesent sit amet ex non eros accumsan consectetur sit amet et odio. Donec sed dolor a lorem viverra viverra. Nam sollicitudin leo eu pharetra mattis. Nullam magna orci, imperdiet eget nulla tempor, pretium aliquet leo. Curabitur faucibus, tortor commodo maximus porta, justo ex pretium turpis, eget iaculis mi magna ac augue. Aliquam sem sem, consequat at urna eu, vulputate posuere tortor. Morbi in orci aliquam lectus fringilla aliquet vel eget turpis. Integer iaculis tortor vitae mollis luctus.
                        </p>
                        <p>
                            Mauris vel ipsum convallis, lacinia diam et, iaculis ligula. Maecenas ac vehicula metus. Suspendisse a augue in enim iaculis blandit. Donec a erat odio. Nullam mollis magna quis pellentesque pharetra. Vestibulum luctus sodales leo sagittis mollis. Mauris blandit, tellus volutpat ultricies ullamcorper, sapien quam condimentum turpis, et bibendum nulla quam ut diam. Nullam lectus quam, elementum ut orci quis, euismod vulputate ante. Nunc ligula arcu, tristique a tincidunt quis, scelerisque eget ex. Nam semper, nunc ut gravida rhoncus, sem nisi malesuada elit, a facilisis tortor velit id magna. Nam dui ex, faucibus nec vestibulum non, lobortis quis sem. Phasellus pretium arcu odio, consectetur vulputate justo auctor sed. Integer sodales ipsum risus, sed mattis lectus commodo ut.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet velit sagittis mauris egestas cursus. Nullam vitae nibh nisi. Suspendisse convallis eros sapien, nec tempor lorem lobortis nec. Cras a faucibus dui. Curabitur ac laoreet turpis, a maximus ligula. Praesent ut lectus ac augue fringilla vehicula sed sit amet dui. Cras nulla mauris, maximus vitae nulla ac, elementum maximus enim. Curabitur fermentum et metus accumsan elementum. In tempus nulla felis, vel porttitor neque semper nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus erat, euismod sed erat vel, condimentum mollis nisl.
                        </p>
                        <p>
                            Sed at augue in felis euismod tincidunt. Mauris vel massa nisl. Quisque iaculis sollicitudin tempor. Suspendisse nec augue ut urna viverra varius sed consectetur nulla. Nunc fringilla ligula nec pulvinar facilisis. Curabitur felis tortor, tempus eget tempor eu, viverra a libero. Sed nisl tellus, mollis quis malesuada nec, mollis quis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vitae tellus vitae nisi interdum molestie. Proin rutrum rhoncus porttitor. Integer sit amet molestie tortor. Nam vel urna eu nisl lobortis ultrices ut a ligula. Aliquam nec facilisis felis, ut porta tellus. Etiam fermentum egestas nisi, eget vestibulum ligula eleifend vitae. Integer pulvinar lectus eget erat porttitor maximus.
                        </p>
                        <p>
                            Integer elit magna, aliquam a auctor eu, commodo sed risus. Maecenas malesuada aliquet urna, convallis feugiat tellus dictum ut. Phasellus eget diam suscipit, scelerisque justo id, faucibus ex. In venenatis sapien ipsum. Morbi semper interdum magna, quis mollis lorem viverra nec. Aliquam erat volutpat. Morbi consequat purus quis nisi laoreet, sed facilisis eros accumsan. Donec suscipit mauris a molestie varius. Aenean sem purus, sollicitudin id lectus quis, egestas dignissim ante. Aenean nibh ex, sollicitudin ac lectus id, condimentum euismod velit. Nulla aliquam, eros vel maximus suscipit, libero nisl suscipit est, quis condimentum justo tortor a urna. Aliquam sollicitudin enim non tempor efficitur.
                        </p>
                        <p>
                            Nam fermentum quam ac faucibus mattis. Fusce mi magna, convallis varius sagittis non, euismod quis sem. Suspendisse ultricies, ante elementum vehicula euismod, arcu quam volutpat diam, eu iaculis lacus tellus eu elit. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nisl accumsan, hendrerit ex quis, luctus nulla. Donec tincidunt lacus quis ex vehicula porta. Praesent sit amet ex non eros accumsan consectetur sit amet et odio. Donec sed dolor a lorem viverra viverra. Nam sollicitudin leo eu pharetra mattis. Nullam magna orci, imperdiet eget nulla tempor, pretium aliquet leo. Curabitur faucibus, tortor commodo maximus porta, justo ex pretium turpis, eget iaculis mi magna ac augue. Aliquam sem sem, consequat at urna eu, vulputate posuere tortor. Morbi in orci aliquam lectus fringilla aliquet vel eget turpis. Integer iaculis tortor vitae mollis luctus.
                        </p>
                        <p>
                            Mauris vel ipsum convallis, lacinia diam et, iaculis ligula. Maecenas ac vehicula metus. Suspendisse a augue in enim iaculis blandit. Donec a erat odio. Nullam mollis magna quis pellentesque pharetra. Vestibulum luctus sodales leo sagittis mollis. Mauris blandit, tellus volutpat ultricies ullamcorper, sapien quam condimentum turpis, et bibendum nulla quam ut diam. Nullam lectus quam, elementum ut orci quis, euismod vulputate ante. Nunc ligula arcu, tristique a tincidunt quis, scelerisque eget ex. Nam semper, nunc ut gravida rhoncus, sem nisi malesuada elit, a facilisis tortor velit id magna. Nam dui ex, faucibus nec vestibulum non, lobortis quis sem. Phasellus pretium arcu odio, consectetur vulputate justo auctor sed. Integer sodales ipsum risus, sed mattis lectus commodo ut.
                        </p>
                    </div>
                </main>
                <Footer/>
                <ModalWindow/>
            </div>
        );
    }
}

ReactDOM.render(<FullSite/>, document.getElementById('app'));

