export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED';

export const POSTPONE_PRODUCT = 'POSTPONE_PRODUCT';

export const SHOW_WAITING_PRODUCTS = 'SHOW_WAITING_PRODUCTS';
export const SHOW_WAITING_PRODUCTS_PENDING = 'SHOW_WAITING_PRODUCTS_PENDING';
export const SHOW_WAITING_PRODUCTS_FULFILLED = 'SHOW_WAITING_PRODUCTS_FULFILLED';
export const SHOW_WAITING_PRODUCTS_REJECTED = 'SHOW_WAITING_PRODUCTS_REJECTED';

export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const GET_SHOPPING_LIST_PENDING = 'GET_SHOPPING_LIST_PENDING';
export const GET_SHOPPING_LIST_FULFILLED = 'GET_SHOPPING_LIST_FULFILLED';
export const GET_SHOPPING_LIST_REJECTED = 'GET_SHOPPING_LIST_REJECTED';

export const GET_QUICK_LIST = 'GET_QUICK_LIST';
export const GET_QUICK_LIST_PENDING = 'GET_QUICK_LIST_PENDING';
export const GET_QUICK_LIST_FULFILLED = 'GET_QUICK_LIST_FULFILLED';
export const GET_QUICK_LIST_REJECTED = 'GET_QUICK_LIST_REJECTED';

